[package]
name = "rust-game-of-life"
version = "0.2.0"
authors = ["ltabis <tab.rysak70@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "*"
